services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: investopedia_app:latest
    container_name: investopedia_app
    ports:
      - "8501:8501"
    volumes:
      - ../:/app
    restart: unless-stopped
